# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "c5fe12d1-0266-4644-926f-acac75cbeafa"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    # api_token: "9bc962214b7b1ceb7abc02ca28187cd28d7a0ead",
    # build_secret: "dff1a2196e5c4320d90bfbec1241b1f1e4c2cac159dd8f47c6ae3e15a1f8d98c"
  )
end
